version: "2"

run:
  tests: true

linters:
  default: all
  disable:
    # keep-sorted start
    - depguard
    - gochecknoglobals
    - gochecknoinits
    - gomodguard
    - noinlineerr
    - wsl
    # keep-sorted end

  settings:
    exhaustruct:
      exclude:
        - '^github\.com/spf13/cobra\.Command$'

formatters:
  enable:
    - gofumpt
    - gci
