version: "2"

run:
  tests: true

linters:
  default: all
  disable:
    # keep-sorted start
    - depguard
    - gomodguard
    - noinlineerr
    - wsl
    # keep-sorted end

formatters:
  enable:
    - gofumpt
    - gci
